// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSuoXbc1VbGWhfFpPZ_lqWtyDEIUM9aPY',
    appId: '1:759271292614:web:82b114cf54e319d513e1c7',
    messagingSenderId: '759271292614',
    projectId: 'hello-flutter-8d157',
    authDomain: 'hello-flutter-8d157.firebaseapp.com',
    storageBucket: 'hello-flutter-8d157.appspot.com',
    measurementId: 'G-YT4DRV92MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaEon-XYBYtVoCFgklgbcXtagKr5Ir6d4',
    appId: '1:759271292614:android:f5978306a903278313e1c7',
    messagingSenderId: '759271292614',
    projectId: 'hello-flutter-8d157',
    storageBucket: 'hello-flutter-8d157.appspot.com',
  );
}
